/**
 * Created by Angel Quispe
 */

module.exports = Object.freeze({
    PROFILE_REGISTER: 'register',
    PROFILE_NOTIFIER: 'notifier',
    PROFILE_ADMIN: 'admin',
    PROFILE_CITIZEN: 'citizen',
    PROFILE_SERVICE: 'service',
    PROFILE_EVALUATOR: 'evaluator',
    PROFILE_REGISTRADOR_NOTIFICADOR: 'register_notifier',
    PROFILE_REGISTER_QUERY: 'consult',
    PATH_BOX: 'box/',
    PATH_CALENDAR: 'calendar/',
    PATH_NOTIFICATION: 'notification/',
    USER_INBOX_PROFILE_OWNER: 'owner',
    USER_INBOX_PROFILE_DELEGATE: 'delegate',
    FILTER_READ: 1,
    FILTER_UNREAD: 2,
    FILTER_NOTIFIED: 3,
    FILTER_NOT_NOTIFIED: 4,
    FILTER_DEFEATED: 5,
    FILTER_NOT_DEFEATED: 6,
    CATALOG_TYPE_ACREDITATION: 'acreditation',
    CATALOG_TYPE_PROCEDURE: 'procedure',
    CATALOG_TYPE_JOB_AREA: 'job_area',
    METADATA_SIGN_PDF: 'metadata.pdf',
    BOX_PDF_RESOLUTION: 'pdf_resolution',
    BOX_PDF_CREATION_SOLICITUDE: 'pdf_creation_solicitude',
    BOX_PDF_AGREE_TOS: 'pdf_agree_tos',
    ERROR_HANDLER: 'error-app',
    JWT_TYPE_AUTH: 'aUth-5is3N',
    TOKEN_PREFIX: 'Bearer ',
    CLARIDAD: 'CLARIDAD',
    SISCOM: 'SISCOM',
    apiKeyClaridad: '68309492-77a7-4697-8510-23712aae1dd2',
    COOKIE_KEY: '0n9E5i3eN$',
    SECRET_KEY: '5iseN-$2022',
    TAM_MAX_NOTI_FILE: 1100 * 1024 * 1024, // 1G mb
    TAM_MAX_FILE: 10 * 1048576, // 10 mb
    TAM_MAX_FILE_CALENDAR: 10 * 1048576, // 3 mb
    MAX_FILES_AUTOMATIC_NOTIFICATION: 3,
    PERSON_TYPE_PN: 'pn',
    PERSON_TYPE_PJ: 'pj',
    NOTIFICATION_SUBJECT_PN: 'Notificación automática - Credenciales del sistema',
    NOTIFICATION_SUBJECT_PJ: 'Notificación automática – Bienvenido',
    NOTIFICATION_EMAIL_BODY_PN: 'Descargue el archivo PDF adjunto, en el se indicará sus Credenciales de Acceso al Sistema',
    NOTIFICATION_EMAIL_BODY_PJ: 'Descargue el archivo PDF adjunto',
    INBOX_STATUS_APROBADO: 'APROBADO',
    URL_REAL_NOTIFICATION: 'https://casillaelectronica.onpe.gob.pe/main/notificaciones-electronicas-detalle/',
    URL_SHORT_NOTIFICATION: 'https://casillaelectronica.onpe.gob.pe/main/get-url/',
    MESSAGE_SEND_NOTIFICATION: 'ONPE - SISEN Te hemos enviado una notificación electrónica, revísala en: ',
    MESSAGE_CREATE_INBOX: 'ONPE - SISEN\nTu solicitud de casilla ha sido aprobada. Consulta tu correo para mas informacion. Si no lo recibiste, comunicate con la ONPE',
    MESSAGE_INBOX_DESAPROBADO: 'ONPE - SISEN\nTu solicitud de casilla ha sido desaprobada. Consulta tu correo para mas informacion. Si no lo recibiste, comunicate con la ONPE',
    PATH_ENV: '/var/www/webservice_admin/.env',
});
